config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    member do
      put 'toggle_public'
    end
    resources :recipe_foods, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
  resources :foods, only: [:index, :show, :new, :create, :destroy]
  resources :public_recipes, only: [:index]
  resources :shopping_list, only: [:index]
  root to: 'foods#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cook_time, presence: true
  validates :description, presence: true

  belongs_to :user, foreign_key: 'user_id', class_name: 'User'
  has_many :recipe_foods, foreign_key: 'recipe_id'
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show destroy]
  before_action :authenticate_user!

  # GET /recipes or /recipes.json
  def index
    @recipes = current_user.recipes
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe_foods = @recipe.recipe_foods
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.recipe_foods.destroy_all
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    respond_to(&:js)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cook_time, :description, :public, :user_id)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.number_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cook_time, style: "display: block" %>
    <%= form.number_field :cook_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.submit "Create Recipe" %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="recipe-show-page">
  <p class="recipe-show-title">
    <%= recipe.name %>
  </p>

  <div class="recipe-show-list">
    <div class="public-private-btn">
      <p class="recipe-show-item">
        <strong>Preparation time:</strong>
        <%= recipe.preparation_time %>
      </p>
      <% if can? :update, recipe %>
        <p>
          <%= button_to(recipe.public ? "Make Private" : "Make Public", toggle_public_recipe_path(recipe), method: :put, remote: true) %>
        </p>
      <% end %>
    </div>

    <p class="recipe-show-item">
      <strong>Cook time:</strong>
      <%= recipe.cook_time %>
    </p>

    <p class="recipe-show-item">
      <strong>Steps go here...</strong>
      <%= recipe.description %>
    </p>
  </div>
  
  <div class="recipe-show-btn">
    <div>
      <% if recipe.user_id == current_user.id %>
        <%= link_to "Generate shopping list", shopping_list_index_path %>
      <% end %>
    </div>
    <div><%= link_to "Add ingredient", new_recipe_recipe_food_path(recipe) %></div>
  </div>

  <table class= "ingredients-table">
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <th>Actions</th>
    </tr>
    <% @recipe_foods.each do |recipe_food| %>
      <tr>
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.quantity %></td>
        <td><%= recipe_food.food.price * recipe_food.quantity %></td>
        <td>
          <div class= "ingredient-btns">
            <% if can? :destroy, recipe %>
              <%= link_to "Modify", edit_recipe_recipe_food_path(recipe, recipe_food) %>
              <%= button_to "Remove", recipe_recipe_food_path(recipe, recipe_food), method: :delete %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="add-recipe-btn">
  <%= link_to "Add recipe", new_recipe_path, class:"add-recipe-link" %>
</div>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <div class="recipe">
      <div class="recipe-name-container">
        <% if recipe.public == true || recipe.user_id == current_user.id%>
          <p>
            <%= link_to recipe.name, recipe %>
          </p>
        <% else %>
          <p>
            <%= recipe.name %>
          </p>
        <% end %>
        <% if recipe.user_id == current_user.id %>
            <%= button_to "Remove", recipe, method: :delete %>
        <% end %>
      </div>
      <p>
        <%= recipe.description %>
      </p>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe %>