config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    member do
      put 'toggle_public'
    end
    resources :recipe_foods, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
  resources :foods, only: [:index, :show, :new, :create, :destroy]
  resources :public_recipes, only: [:index]
  resources :shopping_list, only: [:index]
  root to: 'foods#index'
end

app/views/layouts/_header.html.erb
<% if current_user %>
    <nav class="navbar">
        <ul class="nav-list">
            <li class="nav-items"><%= link_to "Foods", root_path, class:"nav-link" %></li>
            <li class="nav-items"><%= link_to "Recipes", recipes_path, class:"nav-link" %></li>
            <li class="nav-items"><%= link_to "Public Recipes", public_recipes_path, class:"nav-link" %></li>
            <li class="nav-items"><%= link_to "Shopping List", shopping_list_index_path, class:"nav-link" %></li>
            <li class="nav-items"><%= button_to "Log out", destroy_user_session_path, method: :delete, class:"nav-link"%></li>
        </ul>
    </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
      <%= render 'layouts/header' %>
    </header>
    <%= yield %>
  </body>
</html>